# docker build --rm -f Dockerfile.centos -t local/centos .
# docker build --build-arg GO_VERSION=16.x.x-xxxx -f Dockerfile.centos.gocd-agent --rm -t centos/agent . 
FROM local/centos
ARG GO_VERSION="16.8.0-3889"

ENV TINI_VERSION v0.9.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

ADD https://download.go.cd/experimental/binaries/$GO_VERSION/rpm/go-agent-$GO_VERSION.noarch.rpm /tmp/go-agent.rpm

WORKDIR /tmp
RUN yum install -y /tmp/go-agent.rpm; yum clean all; rm -f /etc/default/go-server

# Run your program under Tini
CMD PRODUCTION_MODE=N /usr/share/go-agent/agent.sh
