# Build using: docker build -f Dockerfile.gocd-agent -t gocd-agent .
FROM java:openjdk-7-jre
MAINTAINER Aravind SV <arvind.sv@gmail.com>

WORKDIR /tmp

ENV GOCD_VERSION=16.2.1-3027

RUN curl -L https://download.go.cd/binaries/${GOCD_VERSION}/deb/go-agent-${GOCD_VERSION}.deb >/tmp/go-agent.deb && \
 dpkg -i /tmp/go-agent.deb && \
 curl -L -O https://github.com/Yelp/dumb-init/releases/download/v1.0.0/dumb-init_1.0.0_amd64.deb && \
 dpkg -i /tmp/dumb-init_* && \
 apt-get update && apt-get install sudo && \
 apt-get clean && \
 rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD gocd-agent/go-agent-start.sh /usr/local/bin/go-agent

CMD ["dumb-init", "/usr/local/bin/go-agent"]
