# Build using: docker build -f Dockerfile.gocd-base -t gocd-base .
FROM phusion/baseimage:0.9.18
MAINTAINER GoCD <go-cd-dev@googlegroups.com>

RUN rm -rf /etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh
RUN apt-get update && apt-get install -y -q unzip openjdk-7-jre-headless git mercurial subversion

CMD ["/sbin/my_init"]
