# Build using: docker build --build-arg GO_VERSION=16.x.x-xxxx -f Dockerfile.gocd-agent -t gocd-agent .
FROM gocd/gocd-base
MAINTAINER GoCD <go-cd-dev@googlegroups.com>

ARG GO_VERSION

RUN apt-get update

RUN mkdir /etc/service/go-agent
ADD gocd-agent/go-agent-start.sh /etc/service/go-agent/run

ADD https://download.go.cd/binaries/${GO_VERSION}/deb/go-agent-${GO_VERSION}.deb /tmp/go-agent.deb

WORKDIR /tmp
RUN dpkg -i /tmp/go-agent.deb
RUN sed -i 's/DAEMON=Y/DAEMON=N/' /etc/default/go-agent

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/sbin/my_init"]
