# Build using: docker build --build-arg GO_VERSION=16.x.x-xxxx -f Dockerfile.gocd-dev -t gocd-dev .
FROM gocd/gocd-base
MAINTAINER GoCD <go-cd-dev@googlegroups.com>

ARG GO_VERSION

RUN apt-get update

RUN mkdir /etc/service/go-server
ADD gocd-dev/go-common-scripts.sh /etc/service/go-server/go-common-scripts.sh
ADD gocd-dev/go-server-start.sh /etc/service/go-server/run

RUN mkdir /etc/service/go-agent
ADD gocd-dev/go-common-scripts.sh /etc/service/go-agent/go-common-scripts.sh
ADD gocd-dev/go-agent-start.sh /etc/service/go-agent/run

ADD https://download.go.cd/binaries/${GO_VERSION}/deb/go-server-${GO_VERSION}.deb /tmp/go-server.deb
ADD https://download.go.cd/binaries/${GO_VERSION}/deb/go-agent-${GO_VERSION}.deb /tmp/go-agent.deb

WORKDIR /tmp
RUN dpkg -i /tmp/go-server.deb
RUN dpkg -i /tmp/go-agent.deb
RUN sed -i -e 's/DAEMON=Y/DAEMON=N/' /etc/default/go-server /etc/default/go-agent
RUN echo 'export GO_SERVER_SYSTEM_PROPERTIES="-DpluginLocationMonitor.sleepTimeInSecs=1"' >>/etc/default/go-server
EXPOSE 8153 8154

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/sbin/my_init"]
